### ISSUE TITLE
How to enable Cors for containers? (Embedding Grafana in Organizr)

### ISSUE THREAD

**Issue by bendobos** [Cloudbox/Community#383]
Hello,
I am trying to use a Grafana Dashboard as the Homepage for Organizr. I installed Grafana using the community tag. `security.allow_embedding` is enabled.

When I set the dashboard as the homepage, I get a CORS error:
```
Access to XMLHttpRequest at 'https://grafana.mydomain.com/goto/grafanaid?orgId=1' from origin 'https://organizr.mydomain.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I can not figure out where I can set the headers I need. I tried setting in `/opt/nginx/vhost.d/grafana.mydomain.com` and  `/opt/nginx/vhost.d/grafana.mydomain.com_location` with no luck. 
Editing `default.conf` is not an option since it is generated automatically when starting the container.

**Comment by emwedk** [comment]
pretty sure i made my custom sites work with adding the following to mycustom.mydomain.com

`add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Allow-Credentials' 'true' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With,Range,application/json' always;
add_header 'Access-Control-Max-Age' 1728000;
proxy_cookie_path / "/; SameSite=None; Secure";`

there might be other and better ways of doing so, but i couldn't find them when i had the same issue
